services:
  javascript-unit:
    build:
      context: ..
      dockerfile: cross-sdk-tests/javascript-wrapper/Dockerfile
      target: tester

  python-unit:
    init: true
    build:
      context: ..
      dockerfile: cross-sdk-tests/python-wrapper/Dockerfile
      target: tester

  ruby-unit:
    build:
      context: ..
      dockerfile: cross-sdk-tests/ruby-wrapper/Dockerfile
      target: tester

  java-unit:
    build:
      context: ..
      dockerfile: cross-sdk-tests/java-wrapper/Dockerfile
      target: tester

  php-unit:
    build:
      context: ..
      dockerfile: cross-sdk-tests/php-wrapper/Dockerfile
      target: tester

  go-unit:
    build:
      context: ..
      dockerfile: cross-sdk-tests/go-wrapper/Dockerfile
      target: tester

  dart-unit:
    build:
      context: ..
      dockerfile: cross-sdk-tests/dart-wrapper/Dockerfile
      target: tester

  flutter-unit:
    build:
      context: ..
      dockerfile: cross-sdk-tests/flutter-wrapper/Dockerfile
      target: tester

  swift-unit:
    build:
      context: ..
      dockerfile: cross-sdk-tests/swift-wrapper/Dockerfile
      target: tester

  rust-unit:
    build:
      context: ..
      dockerfile: cross-sdk-tests/rust-wrapper/Dockerfile
      target: tester

  dotnet-unit:
    build:
      context: ..
      dockerfile: cross-sdk-tests/dotnet-wrapper/Dockerfile
      target: tester

  elixir-unit:
    build:
      context: ..
      dockerfile: cross-sdk-tests/elixir-wrapper/Dockerfile
      target: tester

  scala-unit:
    build:
      context: ..
      dockerfile: cross-sdk-tests/scala-wrapper/Dockerfile
      target: tester

  kotlin-unit:
    build:
      context: ..
      dockerfile: cross-sdk-tests/kotlin-wrapper/Dockerfile
      target: tester

  cpp-unit:
    build:
      context: ..
      dockerfile: cross-sdk-tests/cpp-wrapper/Dockerfile
      target: tester

  liquid-unit:
    build:
      context: ..
      dockerfile: cross-sdk-tests/liquid-wrapper/Dockerfile
      target: tester

  react-unit:
    build:
      context: ..
      dockerfile: cross-sdk-tests/react-wrapper/Dockerfile
      target: tester

  vue2-unit:
    build:
      context: ..
      dockerfile: cross-sdk-tests/vue2-wrapper/Dockerfile
      target: tester

  vue3-unit:
    build:
      context: ..
      dockerfile: cross-sdk-tests/vue3-wrapper/Dockerfile
      target: tester

  angular-unit:
    build:
      context: ..
      dockerfile: cross-sdk-tests/angular-wrapper/Dockerfile
      target: tester
